### ISSUE TITLE
build from ci 

### ISSUE THREAD

**Issue by anyaelena** [NREL/OpenStudio-server#392] opened 2018-09-06 17:06 UTC

**Comment by anyaelena** [comment] 2018-09-06 20:28
issue is that building it tends to work on only the build machine

**Comment by anyaelena** [comment] 2019-04-03 16:54
Re-assigning to @tijcolem who is already working on this.

**Comment by tijcolem** [comment] 2020-07-15 17:39
Duplicate of #509

**Closed** 2022-05-05 20:29 UTC
Labels: P1, component - CI
