### ISSUE TITLE
Parallel Coord Filtering Is Bogus

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio-server#203] opened 2017-09-14 23:13 UTC
Digging into the details of an optimization with Parallel Coordinate Plots I found that the filtered data points showing up below the plot are largely bogus.  Here's a filtered plot:

![par1](https://user-images.githubusercontent.com/2230150/30459726-4a45e348-9967-11e7-94df-ac9274acc0b8.png)

It looks like there would only be one solution, but the server thoughtfully suggests:

![par2](https://user-images.githubusercontent.com/2230150/30459737-5bb53156-9967-11e7-8620-25abd548720f.png)

Picking the first point I find:

![par3](https://user-images.githubusercontent.com/2230150/30459756-6c047daa-9967-11e7-9f1b-78c00f31ea22.png)

and...

![par4](https://user-images.githubusercontent.com/2230150/30459765-72a69008-9967-11e7-8086-af5e93a008a9.png)

This point clearly fails the filtering criteria for all four variables "in limit."  Many other points that are identified also fall outside of the filter making it impossible to separate wheat from chaff.  (btw - there are only TWO data points that satisfy the filter criterion.)

**Comment by kflemin** [comment] 2018-01-25 20:17
duplicate of https://github.com/NREL/OpenStudio-server/issues/258

**Closed** 2018-01-25 20:17 UTC
Labels: severity - Normal Bug
