### ISSUE TITLE
Internal 2.6.2 OpenStudio mac installer can't find standards gem

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-server#394] opened 2018-09-11 16:46 UTC
Here is the error I see on local run when trying to use the standards gem.

"[10:41:38.077046 ERROR] /Applications/OpenStudio-2.6.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/util/measure.rb failed with message cannot load such file -- openstudio-standards in /Applications/OpenStudio-2.6.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'

**Comment by anyaelena** [comment] 2018-09-17 21:43
nick added a test for this, but we've been unable to reproduce the error.

**Comment by nllong** [comment] 2018-09-18 13:04
I think I need to understand how you are running the analysis a bit better. Let's chat this week.

**Comment by DavidGoldwasser** [comment] 2018-09-18 19:28
@nllong I was doing a local manual run from PAT in workflow that had measures that required openstudio-standards.

**Comment by rHorsey** [comment] 2018-09-18 20:29
This ticket is a manifestation of a merge error which lead to the CLI not being used - this is being resolved in https://github.com/NREL/OpenStudio-server/pull/393

**Comment by rHorsey** [comment] 2018-09-25 20:09
We believe that this is fixed in the most recent 2.6.2 candidate. @DavidGoldwasser can you please confirm.

**Comment by rHorsey** [comment] 2018-12-12 22:33
lgtm

**Closed by rHorsey** 2018-12-12 22:33 UTC
Labels: P1, blocker, component - local
